python -m pip install --upgrade pip
pip install werkzeug
pip install pypinyin
pip install psutil
pip install pywin32
pip install selenium
pip install threading
pip install xlrd
pip install xlutils
pip install threadpool
pip install requests
pip install ntplib
pip install PyMysql
pip install shutil
pip install ntplib
pip install PyQt5
pip install PySocks
pip install pproxy
pip install requests_html