# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\de_collector.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(363, 219)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(90, 120, 75, 23))
        self.pushButton1.setObjectName("pushButton1")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 60, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 47, 13))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 120, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 363, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "De_collector"))
        self.pushButton1.setText(_translate("MainWindow", "Start"))
        self.comboBox.setItemText(0, _translate("MainWindow", "A"))
        self.comboBox.setItemText(1, _translate("MainWindow", "B"))
        self.comboBox.setItemText(2, _translate("MainWindow", "C"))
        self.comboBox.setItemText(3, _translate("MainWindow", "D"))
        self.comboBox.setItemText(4, _translate("MainWindow", "E"))
        self.comboBox.setItemText(5, _translate("MainWindow", "F"))
        self.comboBox.setItemText(6, _translate("MainWindow", "G"))
        self.comboBox.setItemText(7, _translate("MainWindow", "H"))
        self.comboBox.setItemText(8, _translate("MainWindow", "I"))
        self.comboBox.setItemText(9, _translate("MainWindow", "J"))
        self.comboBox.setItemText(10, _translate("MainWindow", "K"))
        self.comboBox.setItemText(11, _translate("MainWindow", "L"))
        self.comboBox.setItemText(12, _translate("MainWindow", "M"))
        self.comboBox.setItemText(13, _translate("MainWindow", "N"))
        self.comboBox.setItemText(14, _translate("MainWindow", "O"))
        self.comboBox.setItemText(15, _translate("MainWindow", "P"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Q"))
        self.comboBox.setItemText(17, _translate("MainWindow", "R"))
        self.comboBox.setItemText(18, _translate("MainWindow", "S"))
        self.comboBox.setItemText(19, _translate("MainWindow", "T"))
        self.comboBox.setItemText(20, _translate("MainWindow", "U"))
        self.comboBox.setItemText(21, _translate("MainWindow", "V"))
        self.comboBox.setItemText(22, _translate("MainWindow", "W"))
        self.comboBox.setItemText(23, _translate("MainWindow", "X"))
        self.comboBox.setItemText(24, _translate("MainWindow", "Y"))
        self.comboBox.setItemText(25, _translate("MainWindow", "Z"))
        self.label.setText(_translate("MainWindow", "Range"))
        self.pushButton_2.setText(_translate("MainWindow", "Sort"))
